version: '3.8'
services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    working_dir: /notebooks
    ports:
      - 8888:8888
    volumes:
      - ./data/:/data
      - ./notebooks/:/notebooks
